import React, { useMemo, useState } from 'react';
import { ArrowLeft, FilePlus2, Headphones, Play, Sparkles, UsersRound } from 'lucide-react';
import { useData } from '../../context/DataContext';
import { useToolRooms } from '../../context/ToolRoomContext';
import { getToolRoom } from './toolRoomCatalog';
import ToolRoomShell from './ToolRoomShell';
import ToolRoomAIInsight from './ToolRoomAIInsight';
import ChapterDesigner from './ChapterDesigner';
import ChapterWriter from './ChapterWriter';
import CharacterToolRoom from './CharacterToolRoom';
import useToolRoomLaunch from './useToolRoomLaunch';
import { useNarrador } from '../narrador/useNarrador';
import NarradorPanel from '../narrador/NarradorPanel';

const RoomContextBanner = ({ children, status = 'ready' }) => <div className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--border-main)] bg-[var(--bg-editor)] p-4"><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[var(--text-muted)]">Contexto activo</p><p className="mt-1 truncate text-sm font-bold">{children}</p></div><span className={`shrink-0 text-[10px] font-black uppercase tracking-wider ${status === 'pending' ? 'text-amber-500' : 'text-emerald-500'}`}>{status === 'pending' ? 'Requiere selección' : 'Controlado'}</span></div>;

const EmptyRoomState = ({ icon: Icon, title, text }) => <div className="flex min-h-[300px] flex-col items-center justify-center rounded-3xl border border-dashed border-[var(--border-main)] p-8 text-center"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent-main)]">{React.createElement(Icon, { size: 25 })}</div><h2 className="mt-5 text-2xl font-serif font-black">{title}</h2><p className="mt-2 max-w-md text-sm leading-relaxed text-[var(--text-muted)]">{text}</p></div>;

const CoWriterRoom = () => {
    const room = getToolRoom('creative-studio');
    const { chapters = [], characters = [], worldItems = [], activeChapter, selectChapter, createChapter, setActiveView, lazyLoadChapters, updateWorldItem, saveDocumentSnapshot } = useData();
    const { getRoomState, updateRoomState } = useToolRooms();
    const state = getRoomState('creative-studio');
    const [flow, setFlow] = useState(null);
    const selectedChapter = chapters.find((chapter) => chapter.id === state.chapterId) || activeChapter || null;
    const startChapterWriting = ({ structure, plan }) => {
        updateRoomState('creative-studio', { designer: { ...(state.designer || {}), writingStructure: structure, writingPlan: plan } });
        setFlow('writer');
    };
    if (flow === 'character') return <ToolRoomShell room={room} status="ready" context={<RoomContextBanner>Diseñar personaje</RoomContextBanner>}><button type="button" onClick={() => setFlow(null)} className="mb-4 inline-flex items-center gap-2 rounded-xl px-2 py-1.5 text-xs font-black text-[var(--text-muted)] hover:bg-[var(--accent-soft)]"><ArrowLeft size={15} /> Cambiar de flujo</button><CharacterToolRoom /></ToolRoomShell>;
    if (flow === 'writer') return <ToolRoomShell room={room} status="ready" context={<RoomContextBanner>Redactar desde estructura</RoomContextBanner>}><button type="button" onClick={() => setFlow(null)} className="mb-4 inline-flex items-center gap-2 rounded-xl px-2 py-1.5 text-xs font-black text-[var(--text-muted)] hover:bg-[var(--accent-soft)]"><ArrowLeft size={15} /> Cambiar de flujo</button><ChapterWriter state={state} updateRoomState={updateRoomState} worldItems={worldItems} chapters={chapters} characters={characters} activeChapter={activeChapter} lazyLoadChapters={lazyLoadChapters} createChapter={createChapter} selectChapter={selectChapter} setActiveView={setActiveView} onGoDesigner={() => setFlow('designer')} /></ToolRoomShell>;
    if (flow === 'designer') return <ToolRoomShell room={room} status="ready" context={<RoomContextBanner>Diseñar capítulo y escenas</RoomContextBanner>}><button type="button" onClick={() => setFlow(null)} className="mb-4 inline-flex items-center gap-2 rounded-xl px-2 py-1.5 text-xs font-black text-[var(--text-muted)] hover:bg-[var(--accent-soft)]"><ArrowLeft size={15} /> Cambiar de flujo</button><ChapterDesigner state={state} updateRoomState={updateRoomState} worldItems={worldItems} chapters={chapters} characters={characters} activeChapter={activeChapter} lazyLoadChapters={lazyLoadChapters} updateWorldItem={updateWorldItem} saveDocumentSnapshot={saveDocumentSnapshot} onWriteChapter={startChapterWriting} /></ToolRoomShell>;
    return <ToolRoomShell room={room} status="ready" context={<RoomContextBanner>Elige un submodo creativo</RoomContextBanner>}><main className="mx-auto max-w-5xl rounded-3xl border border-[var(--border-main)] bg-[var(--bg-editor)] p-6 lg:p-10"><div className="mx-auto max-w-2xl text-center"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-violet-500">Estudio creativo</p><h2 className="mt-3 text-3xl font-serif font-black sm:text-4xl">Construye antes de escribir</h2><p className="mt-3 text-sm leading-relaxed text-[var(--text-muted)]">Cada submodo produce una propuesta revisable y mantiene el canon separado de la creación.</p></div><div className="mt-9 grid grid-cols-1 gap-4 md:grid-cols-3"><button type="button" onClick={() => setFlow('writer')} className="group rounded-3xl border border-emerald-500/30 bg-emerald-500/5 p-6 text-left transition-all hover:-translate-y-1 hover:border-emerald-500"><FilePlus2 className="text-emerald-500" size={24} /><h3 className="mt-6 text-xl font-serif font-black">Redactar capítulo</h3><p className="mt-2 text-sm leading-relaxed text-[var(--text-muted)]">Convierte una estructura aprobada en un borrador revisable.</p></button><button type="button" onClick={() => setFlow('designer')} className="group rounded-3xl border border-violet-500/30 bg-violet-500/5 p-6 text-left transition-all hover:-translate-y-1 hover:border-violet-500"><Sparkles className="text-violet-500" size={24} /><h3 className="mt-6 text-xl font-serif font-black">Diseñar capítulo</h3><p className="mt-2 text-sm leading-relaxed text-[var(--text-muted)]">Define escenas, conflicto, ritmo y consecuencias antes de redactar.</p></button><button type="button" onClick={() => setFlow('character')} className="group rounded-3xl border border-amber-500/30 bg-amber-500/5 p-6 text-left transition-all hover:-translate-y-1 hover:border-amber-500"><UsersRound className="text-amber-500" size={24} /><h3 className="mt-6 text-xl font-serif font-black">Diseñar personaje</h3><p className="mt-2 text-sm leading-relaxed text-[var(--text-muted)]">Trabaja identidad, psicología, relaciones y trayectoria.</p></button></div>{selectedChapter && <div className="mt-6 rounded-2xl border border-[var(--border-main)] bg-[var(--bg-app)] p-4 text-xs text-[var(--text-muted)]">Capítulo activo: <strong className="text-[var(--text-main)]">{selectedChapter.title}</strong></div>}</main></ToolRoomShell>;
};

const NarratorRoom = () => {
    const room = getToolRoom('narrator');
    const { activeBook, profile, chapters = [], characters = [], worldItems = [], activeChapter, selectChapter, setActiveView } = useData();
    const { getRoomState, updateRoomState } = useToolRooms();
    const state = getRoomState('narrator');
    const launch = useToolRoomLaunch('narrator');
    const selectedChapter = chapters.find((chapter) => chapter.id === (state.chapterId || launch?.context?.chapterIds?.[0])) || activeChapter || null;
    const nextChapter = selectedChapter ? chapters[chapters.findIndex((chapter) => chapter.id === selectedChapter.id) + 1] || null : null;
    const supportingContext = useMemo(() => [...characters.map((character) => `Personaje: ${character.name}\n${character.description || ''}`), ...worldItems.map((item) => `Mundo: ${item.title}\n${item.content || ''}`)].join('\n\n'), [characters, worldItems]);
    const narrador = useNarrador({ editor: null, isFocusMode: false, activeBook, activeChapter: selectedChapter, nextChapter, onSelectChapter: selectChapter, profileData: profile, toast: null });
    return <ToolRoomShell room={room} status={selectedChapter ? 'ready' : 'pending'} context={<RoomContextBanner status={selectedChapter ? 'ready' : 'pending'}>{selectedChapter ? `Contenido aprobado: ${selectedChapter.title}` : 'Selecciona un capítulo para preparar la narración'}</RoomContextBanner>}><div className="grid grid-cols-1 gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="rounded-3xl border border-[var(--border-main)] bg-[var(--bg-editor)] p-4"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-[var(--text-muted)]">Biblioteca de audio</p><h2 className="mt-1 text-lg font-serif font-black">Capítulos</h2><div className="mt-4 space-y-1.5">{chapters.filter((chapter) => !chapter.isVolume).map((chapter) => <button key={chapter.id} type="button" onClick={() => { selectChapter(chapter.id); updateRoomState('narrator', { chapterId: chapter.id }); }} className={`flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left ${selectedChapter?.id === chapter.id ? 'bg-violet-500/10 text-violet-500' : 'hover:bg-[var(--accent-soft)]'}`}><Headphones size={15} /><span className="truncate text-sm font-bold">{chapter.title}</span></button>)}</div></aside><main className="rounded-3xl border border-[var(--border-main)] bg-[var(--bg-editor)] p-5 lg:p-7">{!selectedChapter ? <EmptyRoomState icon={Headphones} title="Prepara una narración" text="Selecciona un capítulo aprobado para generar el guion y sus segmentos." /> : <><NarradorPanel narrador={narrador} activeChapter={selectedChapter} onClose={narrador.stopNarration} /><ToolRoomAIInsight roomName="Narrador" instruction="Convierte el capítulo en un guion de narración con voz, pausas dramáticas y segmentos claros. No cambies el texto original." sourceContent={selectedChapter.content || ''} contextContent={supportingContext} buttonLabel="Generar guion" /><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => setActiveView('editor')} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-main)] px-4 py-3 text-sm font-black hover:border-violet-500"><Play size={16} /> Abrir capítulo</button></div></>}</main></div></ToolRoomShell>;
};

export { CoWriterRoom, NarratorRoom };
